In [2]:
import numpy as np

# Creating Numpy Arrays from Python List

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([3.14,3,4,2.1])

array([3.14, 3.  , 4.  , 2.1 ])

In [5]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [8]:
a2.shape

(2, 3)

In [9]:
a2.ndim

2

In [10]:
a2.dtype

dtype('int32')

In [11]:
a2.size

6

# Creaing Numpt Arays from Numpy

In [13]:
# Hàm Zero
np.zeros((3,4))
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
# Hàm ones
np.ones((3,4))
np.ones((3,4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
# hàm arange
np.arange(1,9)
np.arange(1,11,2,dtype='int')

array([1, 3, 5, 7, 9])

In [17]:
# Hàm Full
np.full((3,4),5,dtype='int')

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [18]:
# Hàm Linspace , chia đều số lượng với khoảng cách
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
# dùng random.seed(0) để taọ ra các ma trận giống nhau mỗi lần random
np.random.seed(0) 
# Hàm random.random() sẽ tạo ra 1 ma trận có giá trị trong khoảng 0-1
np.random.random((4,4))
# hàm tương tự
#np.random.rand(4,4) chỉ cần khai báo shape mà thôi

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [30]:
# Hàm random.randint() return về ma trận int có khoảng được ta chọn
np.random.randint(1,9,(4,4))

array([[7, 8, 1, 2],
       [2, 2, 8, 1],
       [8, 3, 5, 8],
       [4, 7, 4, 3]])

In [31]:
# Hàm random.normal() sẽ return về matrix có phân phối Gaussian
np.random.normal(0,1,(3,4))
# normal(giá trị trung bình,độ lệch chuẩn,size)

array([[ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897]])

# Array Indexing and Slicing
## One dimensional sub array

In [33]:
x1 = np.random.randint(20, size=6)
x1

array([14,  3, 12, 10, 11,  4])

In [36]:
x1[4], x1[0], x1[-1]

(11, 14, 4)

## Multi dimensional array

In [39]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[0, 1, 5, 9],
       [3, 0, 5, 0],
       [1, 2, 4, 2]])

In [40]:
x2[:2,:2]

array([[0, 1],
       [3, 0]])

In [42]:
x2[1,2]

5

In [43]:
x2[1,2] =6
x2

array([[0, 1, 5, 9],
       [3, 0, 6, 0],
       [1, 2, 4, 2]])

## Slicing

In [44]:
x1

array([14,  3, 12, 10, 11,  4])

In [45]:
x1[0:3]

array([14,  3, 12])

In [46]:
x1[0:4:2]

array([14, 12])

In [47]:
x2

array([[0, 1, 5, 9],
       [3, 0, 6, 0],
       [1, 2, 4, 2]])

In [49]:
x2[:2,:3]

array([[0, 1, 5],
       [3, 0, 6]])

In [50]:
x2[:,:2]

array([[0, 1],
       [3, 0],
       [1, 2]])

# Reshape

In [51]:
grid = np.arange(1,10)
grid.shape

(9,)

In [52]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
x3 = np.array([1,2,3])
x3.shape

(3,)

In [58]:
x3.reshape((1,3)).shape

(1, 3)

# Transpose

In [61]:
# Ma trận chuyển vị
x4 = np.array([[1,2,3],[4,5,6]])
x4

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
x4.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Array Concatenation and Splitting

## Concatenation

In [63]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [64]:
np.concatenate((x,y),axis=0)

array([1, 2, 3, 3, 2, 1])

In [67]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate((grid,grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
# hàm vstack
np.vstack((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [72]:
# hàm hstack
np.hstack((grid,grid))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting arrays

In [74]:
x = np.array([1,2,34,5,6,7,8,9])
x

array([ 1,  2, 34,  5,  6,  7,  8,  9])

In [78]:
np.split(x,[3,5])

[array([ 1,  2, 34]), array([5, 6]), array([7, 8, 9])]

In [79]:
x1,x2,x3 = np.split(x,[3,5])

In [80]:
x1

array([ 1,  2, 34])

In [81]:
x2

array([5, 6])

In [82]:
x3

array([7, 8, 9])

# Các phép tính với array

In [83]:
a = np.arange(3)
a

array([0, 1, 2])

In [84]:
a+5

array([5, 6, 7])

In [86]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
b+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

# Những phép toán trên 1 Arrays

In [88]:
list_number = [1,2,3]

In [90]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [91]:
sum(ll)

6

In [92]:
np.sum(ll)

6

In [94]:
big_array = np.random.random(10000)
big_array.shape

(10000,)

In [97]:
%timeit sum(big_array)
%timeit np.sum(big_array)
# thời gian tính toán của các hàm

1.56 ms ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.38 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [102]:
%timeit np.mean(big_array)

6.95 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
np.max(big_array)

0.9999680225821261

In [104]:
np.min(big_array)

4.011685566074341e-06

# Xác Xuất thống kê

In [105]:
#Std : độ lệch chuẩn so với giá trị trung bình
#Var : phương sai

In [106]:
dog_height = [600,400,170,300]
np.std(dog_height)

157.0628854949507

In [107]:
np.var(dog_height)

24668.75

# Sorting array

In [108]:
x = np.array([2,3,5,6,1])

In [109]:
np.sort(x)

array([1, 2, 3, 5, 6])

In [110]:
np.argsort(x) # return index

array([4, 0, 1, 2, 3], dtype=int64)

In [115]:
c  = np.random.randint(0,10,size=(4,6))
c

array([[3, 3, 4, 2, 7, 7],
       [6, 0, 2, 2, 4, 5],
       [5, 7, 9, 0, 2, 3],
       [4, 8, 6, 0, 2, 9]])

In [116]:
np.sort(c,axis=0) # sort theo cột

array([[3, 0, 2, 0, 2, 3],
       [4, 3, 4, 0, 2, 5],
       [5, 7, 6, 2, 4, 7],
       [6, 8, 9, 2, 7, 9]])

In [117]:
np.sort(c,axis=1) # sort theo cột

array([[2, 3, 3, 4, 7, 7],
       [0, 2, 2, 4, 5, 6],
       [0, 2, 3, 5, 7, 9],
       [0, 2, 4, 6, 8, 9]])

# Đại số tuyến tính

In [119]:
a = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [120]:
b = np.array([[6,5],[4,3],[2,1]])

In [123]:
a.shape, b.shape

((3, 3), (3, 2))

In [121]:
a.dot(b)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [124]:
# tương tự
a@b

array([[20, 14],
       [56, 41],
       [92, 68]])

In [128]:
b.T.dot(a)

array([[36, 48, 60],
       [24, 33, 42]])

In [130]:
b.T @ a

array([[36, 48, 60],
       [24, 33, 42]])

# Example Dot product

In [132]:
np.random.seed(0)
sale_amouts = np.random.randint(20,size=(5,3))
sale_amouts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [134]:
import pandas as pd
weekly = pd.DataFrame(sale_amouts, index=['mon','tue','wed','thus','fri'],
columns=['pep','cola','aka'])

In [135]:
weekly.head()

pep  cola  aka
mon    12    15    0
tue     3     3    7
wed     9    19   18
thus    4     6   12
fri     1     6    7

In [145]:
price =np.array([10,8,12])
drink_price = pd.DataFrame(price.reshape(1,3),index=['Prices'],columns=['pep','cola','aka'])

In [146]:
drink_price

pep  cola  aka
Prices   10     8   12

In [147]:
weekly.shape, drink_price.shape

((5, 3), (1, 3))

In [148]:
total_price = weekly.dot(drink_price.T)

In [149]:
total_price

Prices
mon      240
tue      138
wed      458
thus     232
fri      142

In [150]:
weekly['Total_price'] = total_price
weekly


pep  cola  aka  Total_price
mon    12    15    0          240
tue     3     3    7          138
wed     9    19   18          458
thus    4     6   12          232
fri     1     6    7          142